/*
Заполнение основных таблиц

+users;
+images;
+user_profiles;
*/

INSERT INTO users (phone,is_confirmed_phone,email,is_confirmed_email,authorization_type)
VALUES
  ('1-237-853-3159','True','ut.nisi@hotmail.net','False',1),
  ('1-565-998-0806','False','sit@google.com','False',3),
  ('(572) 293-8543','True','dui@outlook.ca','True',2),
  ('1-848-117-0762','False','egestas.blandit.nam@aol.com','False',3),
  ('(658) 458-9565','True','morbi.vehicula@outlook.ca','False',4),
  ('1-976-478-5340','True','gravida.mauris@outlook.edu','False',2),
  ('1-633-572-8147','False','felis.adipiscing@google.com','False',3),
  ('(708) 227-6961','True','mi.ac.mattis@aol.couk','True',2),
  ('1-162-629-7284','False','bibendum.ullamcorper@protonmail.couk','True',4),
  ('1-459-345-9322','False','sit.amet@outlook.net','False',3),
  ('(787) 741-4860','False','ante@yahoo.edu','False',4),
  ('(971) 464-2186','False','per.conubia@protonmail.org','False',3),
  ('(594) 449-6154','True','nulla@icloud.ca','False',2),
  ('(429) 542-8427','True','orci.sem.eget@hotmail.edu','True',4),
  ('(174) 375-7667','True','massa1@google.net','True',3),
  ('(942) 291-2561','True','ac.mattis@protonmail.org','False',1),
  ('1-867-410-6061','False','orci.consectetuer@protonmail.net','False',1),
  ('(687) 340-7797','True','vestibulum.accumsan@aol.edu','True',3),
  ('1-746-515-4516','True','risus.odio@outlook.couk','True',3),
  ('(615) 457-6482','True','in.hendrerit@google.com','True',4),
  ('(516) 606-6892','False','neque@google.com','True',1),
  ('(963) 686-5371','True','tempor@protonmail.edu','False',2),
  ('1-976-880-4372','True','arcu.vel@hotmail.edu','True',2),
  ('1-751-554-2155','False','sociis.natoque@google.org','False',2),
  ('1-347-942-6075','True','molestie.in@icloud.net','False',3),
  ('1-948-118-0648','False','ligula@protonmail.edu','False',3),
  ('1-483-247-8843','False','imperdiet.erat@outlook.couk','False',1),
  ('1-727-282-2335','True','a.mi@aol.couk','False',3),
  ('1-915-577-2567','False','magna@protonmail.com','True',2),
  ('1-635-334-7316','True','magnis.dis@google.org','False',4);
INSERT INTO users (phone,is_confirmed_phone,email,is_confirmed_email,authorization_type)
VALUES
  ('(701) 552-6981','False','id.mollis.nec@aol.couk','False',4),
  ('1-321-762-6457','False','eu.ligula@yahoo.edu','False',2),
  ('1-543-737-4226','True','commodo.tincidunt@protonmail.couk','False',2),
  ('1-567-307-9826','False','massa@google.net','False',2),
  ('1-568-531-4522','False','ut@aol.com','False',2),
  ('1-856-651-3368','True','aptent.taciti@outlook.com','True',2),
  ('(688) 609-4464','True','nec.urna.et@google.edu','False',4),
  ('(126) 508-3884','False','gravida.aliquam@outlook.ca','False',4),
  ('1-626-627-5565','True','nunc@protonmail.org','False',2),
  ('1-853-809-7328','True','maecenas.mi@aol.com','False',2),
  ('1-647-885-7606','True','nec.urna.suscipit@protonmail.net','True',1),
  ('(624) 257-8668','False','auctor@aol.net','False',3),
  ('(231) 587-9417','False','quam@protonmail.couk','True',3),
  ('(773) 248-7456','True','imperdiet.non.vestibulum@google.net','True',2),
  ('1-143-293-8281','False','lorem@google.net','False',2),
  ('(374) 613-9273','False','id@aol.ca','True',2),
  ('1-719-577-6214','False','et.rutrum@yahoo.net','True',3),
  ('(789) 621-2455','True','lobortis@hotmail.ca','False',2),
  ('(951) 534-1869','False','hendrerit.a.arcu@protonmail.net','True',3),
  ('1-284-761-6728','True','pellentesque.sed@yahoo.ca','False',3);
INSERT INTO users (phone,is_confirmed_phone,email,is_confirmed_email,authorization_type)
VALUES
  ('(668) 149-7657','False','tellus.id@yahoo.org','True',1),
  ('1-762-355-2602','False','turpis.nulla@protonmail.ca','False',2),
  ('(893) 740-3876','False','ullamcorper.nisl@hotmail.ca','False',3),
  ('1-308-119-4445','False','elementum.lorem@hotmail.net','True',2),
  ('1-393-874-6425','True','quisque.fringilla@google.ca','False',2),
  ('(434) 463-8147','False','sed.auctor@aol.com','False',3),
  ('(748) 884-7109','True','neque.venenatis@protonmail.couk','False',4),
  ('(278) 949-6138','True','in.sodales@protonmail.org','False',3),
  ('1-351-719-1387','True','nulla.tempor@icloud.com','False',4),
  ('1-613-775-4785','False','fringilla@outlook.org','False',2),
  ('(366) 436-7045','True','vulputate@google.net','True',1),
  ('(314) 251-1408','False','sed.nec@google.ca','True',2),
  ('(398) 726-3618','True','elit.fermentum.risus@hotmail.com','False',2),
  ('(680) 668-3420','True','eros.proin@hotmail.edu','False',2),
  ('1-423-759-3127','False','nulla.integer@icloud.com','True',2),
  ('1-362-946-9047','False','nunc.quis@icloud.ca','True',4),
  ('(441) 982-8823','True','amet.dapibus@aol.net','False',2),
  ('1-493-913-5245','True','ullamcorper@yahoo.edu','False',3),
  ('(662) 458-8453','False','neque@outlook.edu','False',3),
  ('(229) 219-7616','True','lorem.ipsum@yahoo.org','True',3),
  ('(955) 267-0527','False','amet@yahoo.org','True',4),
  ('(347) 348-5514','False','egestas.lacinia.sed@outlook.ca','False',4),
  ('1-908-487-5643','False','laoreet.ipsum.curabitur@yahoo.ca','False',2),
  ('(556) 665-9806','True','neque.sed.dictum@google.couk','False',3),
  ('(669) 835-4459','True','sagittis.semper@protonmail.edu','True',2),
  ('1-483-341-0743','True','eu@protonmail.couk','True',4),
  ('(817) 379-9850','True','donec@google.couk','False',2),
  ('(768) 378-2867','False','sed.nunc@google.couk','False',1),
  ('1-323-793-2116','False','ac.mattis@google.ca','False',2),
  ('1-987-778-1832','True','libero.dui.nec@outlook.edu','True',4);
INSERT INTO users (phone,is_confirmed_phone,email,is_confirmed_email,authorization_type)
VALUES
  ('(876) 130-7906','True','pellentesque.sed@google.org','True',1),
  ('1-421-327-6893','True','tortor.nunc@protonmail.org','False',1),
  ('1-402-637-7197','True','tincidunt@protonmail.com','False',1),
  ('(165) 867-7764','True','cursus@aol.org','False',4),
  ('(734) 664-6671','True','bibendum@outlook.couk','True',4),
  ('(623) 640-8301','False','nullam.ut@yahoo.com','False',1),
  ('(436) 333-0169','False','dolor@outlook.ca','False',2),
  ('1-819-945-1882','True','urna@yahoo.ca','True',3),
  ('(436) 414-3606','True','viverra.maecenas@protonmail.com','True',2),
  ('(832) 686-7833','False','vel.mauris@yahoo.org','True',1),
  ('1-748-522-0786','True','inceptos.hymenaeos@outlook.org','True',2),
  ('(315) 158-8842','True','sapien.nunc@aol.net','True',3),
  ('(385) 648-8142','True','in.cursus.et@protonmail.edu','False',4),
  ('(635) 832-1167','True','etiam@outlook.couk','True',4),
  ('1-971-726-3449','False','dolor.dolor.tempus@protonmail.ca','False',2),
  ('(284) 150-5742','False','erat.volutpat.nulla@protonmail.edu','False',2),
  ('(522) 872-5708','True','semper.dui@protonmail.org','False',3),
  ('(241) 648-7173','False','suspendisse@google.ca','True',2),
  ('1-314-134-3423','False','faucibus.morbi.vehicula@aol.couk','True',2),
  ('1-556-478-6297','True','sed@icloud.edu','False',3);
INSERT INTO users (phone,is_confirmed_phone,email,is_confirmed_email,authorization_type)
VALUES
  ('(314) 323-5197','True','morbi@hotmail.com','True',3),
  ('(534) 954-0786','False','et.malesuada.fames@outlook.com','True',2),
  ('1-782-705-3925','False','sollicitudin.commodo.ipsum@icloud.edu','True',2),
  ('(317) 651-5861','True','augue.id@outlook.ca','False',1),
  ('1-828-124-9512','False','aliquam.arcu@icloud.net','True',1),
  ('1-572-770-6417','True','elit@yahoo.couk','False',3),
  ('(857) 461-5255','True','cursus.et@google.net','True',2),
  ('1-847-551-8917','True','diam.nunc.ullamcorper@outlook.couk','True',2),
  ('1-889-868-8802','False','donec@icloud.org','False',3),
  ('(885) 334-6062','False','molestie.orci@google.org','False',3),
  ('(631) 721-8633','False','eget.lacus@aol.couk','True',3),
  ('(667) 376-4751','False','aliquam.fringilla@yahoo.couk','True',3),
  ('1-795-617-1841','True','metus.in@outlook.net','False',1),
  ('(472) 482-5976','True','facilisi.sed@protonmail.org','False',4),
  ('1-729-875-6569','False','odio.phasellus@hotmail.com','True',2),
  ('1-771-641-7818','False','purus.maecenas.libero@aol.edu','True',3),
  ('1-597-574-2495','False','odio.sagittis.semper@hotmail.edu','False',3),
  ('(631) 481-1415','True','vehicula.aliquet@protonmail.org','True',2),
  ('1-593-542-8858','True','odio.semper@yahoo.ca','True',2),
  ('1-854-418-2221','False','fusce@hotmail.edu','False',3),
  ('1-964-840-4666','False','erat@hotmail.org','False',4),
  ('(829) 660-2782','True','ut.pharetra@yahoo.com','True',1),
  ('(794) 866-2256','False','neque.non@aol.org','True',1),
  ('(588) 696-3426','False','vitae.semper@icloud.edu','True',4),
  ('(532) 214-7631','False','donec.feugiat@yahoo.org','True',2),
  ('1-231-677-5659','True','semper@outlook.com','False',3),
  ('1-834-460-5312','True','ut.mi@google.org','True',3),
  ('(450) 871-5218','False','iaculis@aol.org','False',1),
  ('(330) 109-7451','False','penatibus.et@protonmail.org','True',2),
  ('(283) 413-9202','True','pharetra.ut@yahoo.edu','True',3);
INSERT INTO users (phone,is_confirmed_phone,email,is_confirmed_email,authorization_type)
VALUES
  ('1-614-438-7430','False','magnis.dis@google.couk','False',3),
  ('1-263-884-4202','True','cursus.a@protonmail.ca','True',4),
  ('(363) 219-8583','True','cras@icloud.couk','False',1),
  ('1-235-182-3570','True','luctus.curabitur@outlook.net','False',1),
  ('1-373-726-6385','False','penatibus.et.magnis@protonmail.com','False',3),
  ('(624) 640-5143','True','lorem.lorem.luctus@aol.net','False',3),
  ('1-916-215-5188','True','semper.tellus@icloud.net','True',1),
  ('1-676-942-0586','False','magnis.dis.parturient@outlook.com','False',2),
  ('(242) 688-2865','False','sed.pede@icloud.org','False',3),
  ('(452) 784-0561','False','et.magna.praesent@google.ca','True',4),
  ('1-754-898-0314','False','ipsum@yahoo.com','True',2),
  ('(985) 877-6104','True','dictum.eleifend@hotmail.couk','False',1),
  ('1-301-189-4642','False','vitae@google.couk','True',1),
  ('(337) 340-7523','True','nec.eleifend.non@yahoo.couk','False',2),
  ('1-106-253-2416','True','sodales.purus@hotmail.net','False',3),
  ('1-576-900-4717','False','ante.vivamus@protonmail.couk','True',3),
  ('(646) 474-4379','False','nullam@google.net','True',3),
  ('1-229-504-5893','False','libero.nec.ligula@hotmail.net','False',4),
  ('(411) 456-1757','True','nisi.magna@hotmail.net','True',2),
  ('1-968-753-4839','False','auctor.odio@google.org','True',3); 


--images
INSERT INTO images (image_type_id,image_url)
VALUES
  (3,'https://netflix.com/site?q=0'),
  (2,'http://twitter.com/sub?search=1'),
  (2,'https://naver.com/en-us?g=1'),
  (3,'https://whatsapp.com/user/110?client=g'),
  (3,'http://cnn.com/settings?page=1&offset=1'),
  (4,'https://walmart.com/sub/cars?p=8'),
  (4,'http://ebay.com/en-us?q=4'),
  (4,'http://whatsapp.com/sub?q=4'),
  (4,'https://facebook.com/sub/cars?ad=115'),
  (3,'https://walmart.com/fr?client=g'),
  (5,'https://baidu.com/sub/cars?ad=115'),
  (4,'http://netflix.com/settings?search=1&q=de'),
  (5,'http://walmart.com/sub?ab=441&aad=2'),
  (2,'http://google.com/sub?q=test'),
  (1,'http://walmart.com/one?search=1&q=de'),
  (6,'https://bbc.co.uk/en-us?ab=441&aad=2'),
  (3,'https://ebay.com/site?q=0'),
  (3,'https://facebook.com/site?p=8'),
  (4,'http://nytimes.com/settings?q=11'),
  (3,'https://bbc.co.uk/site?gi=100'),
  (4,'https://ebay.com/site?search=1'),
  (4,'https://twitter.com/sub/cars?str=se'),
  (4,'https://google.com/group/9?client=g'),
  (6,'http://ebay.com/sub/cars?k=0'),
  (3,'http://facebook.com/one?p=8'),
  (6,'https://nytimes.com/en-us?search=1'),
  (4,'https://baidu.com/one?q=test'),
  (3,'http://wikipedia.org/site?q=11'),
  (2,'http://guardian.co.uk/group/9?q=0'),
  (5,'http://ebay.com/settings?str=se');
INSERT INTO images (image_type_id,image_url)
VALUES
  (6,'http://zoom.us/site?g=1'),
  (1,'https://reddit.com/en-us?k=0'),
  (4,'https://nytimes.com/one?q=4'),
  (2,'https://youtube.com/user/110?q=11'),
  (5,'http://twitter.com/fr?gi=100'),
  (4,'http://reddit.com/en-us?k=0'),
  (4,'http://baidu.com/user/110?search=1'),
  (3,'https://pinterest.com/en-ca?g=1'),
  (6,'https://baidu.com/fr?p=8'),
  (3,'https://naver.com/one?q=11'),
  (3,'https://naver.com/en-us?gi=100'),
  (4,'https://ebay.com/sub?k=0'),
  (1,'https://facebook.com/fr?q=11'),
  (4,'https://nytimes.com/en-us?search=1&q=de'),
  (4,'http://ebay.com/user/110?k=0'),
  (3,'http://cnn.com/fr?q=4'),
  (2,'https://cnn.com/user/110?gi=100'),
  (4,'https://wikipedia.org/fr?page=1&offset=1'),
  (1,'http://nytimes.com/sub?gi=100'),
  (2,'https://cnn.com/sub/cars?q=11');
INSERT INTO images (image_type_id,image_url)
VALUES
  (6,'http://twitter.com/fr?ab=441&aad=2'),
  (2,'http://nytimes.com/sub?g=1'),
  (3,'http://youtube.com/fr?search=1&q=de'),
  (3,'https://bbc.co.uk/user/110?q=11'),
  (5,'https://wikipedia.org/en-ca?q=test'),
  (5,'https://reddit.com/sub/cars?page=1&offset=1'),
  (4,'http://bbc.co.uk/en-ca?str=se'),
  (2,'http://guardian.co.uk/fr?str=se'),
  (6,'https://walmart.com/sub?g=1'),
  (2,'http://wikipedia.org/one?k=0'),
  (1,'http://naver.com/group/9?g=1'),
  (3,'http://naver.com/group/9?search=1'),
  (5,'http://google.com/sub?q=0'),
  (5,'https://zoom.us/en-us?ab=441&aad=2'),
  (4,'http://yahoo.com/group/9?q=0'),
  (4,'http://zoom.us/group/9?str=se'),
  (3,'https://google.com/settings?client=g'),
  (2,'http://bbc.co.uk/fr?search=1&q=de'),
  (4,'http://ebay.com/fr?client=g'),
  (4,'https://baidu.com/en-ca?q=0'),
  (5,'http://yahoo.com/fr?p=8'),
  (4,'http://walmart.com/one?client=g'),
  (2,'https://ebay.com/settings?page=1&offset=1'),
  (5,'https://twitter.com/user/110?k=0'),
  (5,'https://pinterest.com/site?q=4'),
  (5,'https://ebay.com/fr?p=8'),
  (2,'http://naver.com/settings?ab=441&aad=2'),
  (2,'http://bbc.co.uk/sub/cars?gi=100'),
  (4,'https://netflix.com/settings?gi=100'),
  (5,'http://zoom.us/sub/cars?ad=115');
INSERT INTO images (image_type_id,image_url)
VALUES
  (4,'http://google.com/one?gi=100'),
  (4,'http://youtube.com/one?ad=115'),
  (3,'https://netflix.com/user/110?search=1&q=de'),
  (5,'http://nytimes.com/sub/cars?page=1&offset=1'),
  (4,'https://naver.com/site?q=test'),
  (5,'http://yahoo.com/sub/cars?q=0'),
  (6,'http://netflix.com/site?g=1'),
  (5,'http://ebay.com/sub/cars?ad=115'),
  (4,'http://yahoo.com/site?g=1'),
  (5,'https://twitter.com/sub?str=se'),
  (3,'http://wikipedia.org/en-ca?p=8'),
  (3,'https://youtube.com/group/9?k=0'),
  (4,'http://youtube.com/en-us?ad=115'),
  (6,'https://bbc.co.uk/settings?q=11'),
  (2,'https://pinterest.com/fr?q=11'),
  (4,'https://baidu.com/settings?p=8'),
  (3,'http://youtube.com/sub?ad=115'),
  (2,'https://twitter.com/user/110?ad=115'),
  (2,'http://pinterest.com/sub?q=0'),
  (1,'https://naver.com/en-us?search=1&q=de');
INSERT INTO images (image_type_id,image_url)
VALUES
  (4,'https://nytimes.com/en-ca?gi=100'),
  (4,'https://walmart.com/settings?page=1&offset=1'),
  (6,'https://ebay.com/sub?g=1'),
  (3,'http://yahoo.com/sub/cars?str=se'),
  (6,'http://bbc.co.uk/fr?ab=441&aad=2'),
  (4,'https://guardian.co.uk/settings?p=8'),
  (3,'http://baidu.com/one?page=1&offset=1'),
  (4,'http://twitter.com/en-ca?p=8'),
  (1,'https://twitter.com/site?page=1&offset=1'),
  (5,'https://youtube.com/one?client=g'),
  (6,'http://yahoo.com/one?q=11'),
  (4,'http://zoom.us/user/110?q=0'),
  (1,'https://ebay.com/sub/cars?k=0'),
  (4,'https://baidu.com/user/110?client=g'),
  (3,'https://whatsapp.com/settings?g=1'),
  (5,'http://cnn.com/group/9?g=1'),
  (4,'http://whatsapp.com/one?str=se'),
  (2,'http://facebook.com/group/9?q=0'),
  (4,'http://pinterest.com/en-us?search=1'),
  (5,'https://guardian.co.uk/site?gi=100'),
  (1,'https://google.com/fr?q=0'),
  (5,'https://zoom.us/fr?search=1'),
  (2,'https://guardian.co.uk/group/9?k=0'),
  (2,'http://walmart.com/sub/cars?g=1'),
  (3,'https://google.com/en-us?g=1'),
  (4,'http://baidu.com/sub/cars?gi=100'),
  (6,'https://yahoo.com/fr?p=8'),
  (2,'https://cnn.com/user/110?p=8'),
  (3,'http://reddit.com/sub?gi=100'),
  (3,'https://google.com/settings?g=1');
INSERT INTO images (image_type_id,image_url)
VALUES
  (1,'https://baidu.com/fr?str=se'),
  (3,'https://facebook.com/sub/cars?q=11'),
  (5,'http://guardian.co.uk/one?search=1&q=de'),
  (4,'http://google.com/one?q=4'),
  (5,'https://twitter.com/sub?q=4'),
  (4,'http://reddit.com/site?ab=441&aad=2'),
  (5,'https://youtube.com/one?k=0'),
  (6,'http://pinterest.com/sub/cars?search=1&q=de'),
  (5,'https://pinterest.com/user/110?g=1'),
  (4,'https://instagram.com/fr?q=test'),
  (6,'http://twitter.com/sub/cars?q=4'),
  (4,'http://ebay.com/en-ca?p=8'),
  (5,'http://pinterest.com/settings?p=8'),
  (1,'https://reddit.com/sub?search=1'),
  (4,'http://instagram.com/user/110?gi=100'),
  (1,'https://naver.com/sub?ad=115'),
  (6,'http://baidu.com/sub?search=1'),
  (2,'https://reddit.com/site?q=4'),
  (5,'http://yahoo.com/group/9?search=1&q=de'),
  (1,'https://youtube.com/en-us?search=1&q=de'); 

--user_profiles;
INSERT INTO user_profiles (name,surname,gender,birthday,country,locality,personal_site,vk,twitter,about_yourself,avatar_image_id,user_id)
VALUES
  ('Josephine','Frye','male','1956-11-13','Singapore','Lauro de Freitas','http://whatsapp.com/group/9','https://ebay.com/sub?p=8','http://baidu.com/settings?k=0','in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam',24,1),
  ('Kylan','Cotton','male','1984-03-27','India','La Pintana','https://news.mail.ru/group/9','http://netflix.com/fr?k=0','https://naver.com/en-us?p=8','non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna',20,2),
  ('George','Hester','male','1965-04-06','Chile','Volgograd','https://dns-shop.ru/sub/cars','https://ebay.com/sub/cars?p=8','https://google.com/site?ad=115','velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget',21,3),
  ('Craig','Shannon','male','1982-06-04','China','Ereğli','http://netflix.com/sub','https://walmart.com/fr?q=0','http://netflix.com/user/110?client=g','aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh',11,4),
  ('Melyssa','Vasquez','male','1957-04-05','Colombia','Pamplona','http://mail.ru/sub/cars','https://instagram.com/site?gi=100','https://nytimes.com/fr?k=0','euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu.',5,5),
  ('Ella','Brennan','male','2014-02-10','Belgium','Phan Thiết','https://aliex/en-us','http://instagram.com/en-us?str=se','https://bbc.co.uk/fr?str=se','amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor',70,6),
  ('Todd','Patton','male','2014-06-04','Indonesia','Iquitos','https://livejournal.com/user/110','https://guardian.co.uk/settings?k=0','http://bbc.co.uk/sub/cars?ab=441&aad=2','sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget',76,7),
  ('Keith','Haney','male','1967-11-01','South Africa','Savona','https://kinopoisk.ru/settings','http://ebay.com/sub?k=0','http://cnn.com/en-us?q=11','Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede',128,8),
  ('Nadine','Scott','male','1981-05-24','France','Envigado','http://kommersant.ru/user/110','http://guardian.co.uk/site?g=1','http://facebook.com/site?q=test','nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui.',37,9),
  ('Candice','Palmer','male','2007-11-21','Austria','Puno','https://mk.ru/site','https://baidu.com/group/9?str=se','http://netflix.com/sub/cars?str=se','Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed',93,10),
  ('Mari','Mcintyre','male','2005-01-02','Poland','Ways','http://fandom.com/en-us','http://nytimes.com/site?q=11','http://nytimes.com/group/9?q=4','aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris',30,11),
  ('Clinton','West','male','1967-12-18','Germany','Sibasa','https://wikipedia.org/sub','https://zoom.us/sub?search=1','https://nytimes.com/en-ca?k=0','ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et',126,12),
  ('Roth','Stone','male','1967-08-05','United States','Fauske','http://sports.ru/sub','https://yahoo.com/sub/cars?search=1&q=de','http://netflix.com/site?search=1&q=de','pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in',119,13),
  ('Hiroko','Kidd','male','1995-02-05','Mexico','Mata de Plátano','http://wikipedia.org/en-ca','http://guardian.co.uk/sub/cars?q=test','http://yahoo.com/user/110?k=0','Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris',54,14),
  ('Ezekiel','Barr','male','1990-04-15','Singapore','Şanlıurfa','http://turbopages.org/en-us','https://guardian.co.uk/settings?q=test','http://nytimes.com/site?q=0','sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris.',36,15),
  ('Fatima','Tyler','male','2003-01-09','United Kingdom','Soledad','http://fandom.com/one','https://reddit.com/group/9?ad=115','http://reddit.com/one?q=4','est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit',135,16),
  ('Carol','Sheppard','male','1985-11-15','Germany','Châteauroux','https://drive2.ru/sub/cars','https://baidu.com/settings?search=1&q=de','https://walmart.com/site?gi=100','at fringilla purus mauris a nunc. In at pede. Cras vulputate velit',120,17),
  ('John','Cash','male','2002-06-23','Peru','Shreveport','http://championat.com/user/110','http://instagram.com/en-ca?g=1','https://instagram.com/sub/cars?q=11','non, feugiat nec, diam. Duis mi enim, condimentum eget,',36,18),
  ('Zena','Mcpherson','male','1998-12-26','Turkey','Sens','http://rambler.ru/fr','http://naver.com/fr?ad=115','https://zoom.us/group/9?q=0','auctor, velit eget laoreet posuere, enim nisl elementum purus,',80,19),
  ('Joan','Oneal','male','1975-11-01','Ukraine','Pangkalpinang','http://whatsapp.com/fr','https://guardian.co.uk/sub/cars?page=1&offset=1','https://yahoo.com/en-us?ab=441&aad=2','Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem',91,20),
  ('Tasha','Petersen','male','1950-07-09','Costa Rica','Liberia','http://whatsapp.com/en-ca','http://instagram.com/group/9?gi=100','http://whatsapp.com/one?client=g','malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis',46,21),
  ('Noelle','Hall','male','1984-06-07','Spain','Erciş','http://google.com/en-us','https://baidu.com/sub/cars?q=test','http://guardian.co.uk/settings?q=11','sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et',113,22),
  ('Shoshana','Dale','male','1968-02-01','Spain','Neu-Isenburg','http://whatsapp.com/site','https://twitter.com/sub?page=1&offset=1','https://facebook.com/fr?search=1','dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna.',28,23),
  ('Belle','Yates','male','1971-01-15','United States','Rostov','https://bbc.co.uk/settings','https://zoom.us/sub/cars?ad=115','http://twitter.com/group/9?client=g','Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec',53,24),
  ('Hyatt','Huff','male','1958-07-20','Australia','Galway','http://pikabu.ru/fr','https://walmart.com/en-ca?q=11','http://reddit.com/settings?p=8','Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque',52,25),
  ('Darrel','Ortiz','male','1977-09-22','Germany','Burgos','http://pinterest.com/user/110','http://yahoo.com/user/110?q=11','http://wikipedia.org/en-ca?page=1&offset=1','sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie',86,26),
  ('Ina','Carey','male','1961-01-21','Turkey','Klerksdorp','http://tiktok.com/site','https://pinterest.com/one?search=1','http://guardian.co.uk/fr?g=1','scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in,',69,27),
  ('Ryder','Aguirre','male','2003-09-24','Singapore','Pinetown','http://vz.ru/group/9','http://instagram.com/site?ab=441&aad=2','https://naver.com/sub/cars?ab=441&aad=2','adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu',121,28),
  ('Carolyn','Bartlett','male','1977-10-13','United States','Tampines','https://kinopoisk.ru/group/9','https://whatsapp.com/sub?client=g','https://ebay.com/group/9?ab=441&aad=2','sem egestas blandit. Nam nulla magna, malesuada vel, convallis in,',77,29),
  ('Hayley','Brock','male','1956-01-20','United Kingdom','Baubau','http://pinterest.com/group/9','https://pinterest.com/user/110?client=g','https://ebay.com/en-ca?page=1&offset=1','dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non,',75,30);
INSERT INTO user_profiles (name,surname,gender,birthday,country,locality,personal_site,vk,twitter,about_yourself,avatar_image_id,user_id)
VALUES
  ('Vanna','Estes','male','2013-01-24','New Zealand','Masterton','https://market.yandex.ru/en-us','https://netflix.com/one?client=g','http://guardian.co.uk/site?ad=115','neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc',27,31),
  ('Olympia','Prince','male','1953-04-15','Italy','Limache','http://news.mail.ru/fr','https://instagram.com/user/110?q=0','http://bbc.co.uk/fr?q=test','Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim,',86,32),
  ('Felicia','Witt','male','1992-01-19','Ireland','Vetlanda','http://ria.ru/sub/cars','http://cnn.com/sub?k=0','http://pinterest.com/en-us?client=g','orci luctus et ultrices posuere cubilia Curae Donec tincidunt. Donec vitae erat vel pede',2,33),
  ('Jescie','Foreman','male','1961-02-22','India','Guadalupe','https://gosuslugi.ru/fr','http://instagram.com/fr?ab=441&aad=2','https://naver.com/group/9?ad=115','Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse',20,34),
  ('Martena','Burks','male','1993-08-05','Russian Federation','Kaluga','http://mk.ru/settings','https://walmart.com/fr?ab=441&aad=2','http://pinterest.com/user/110?ad=115','Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque',97,35),
  ('Ali','Forbes','male','1989-12-27','Costa Rica','Cần Thơ','https://vz.ru/sub/cars','http://facebook.com/group/9?gi=100','http://netflix.com/fr?k=0','eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt,',67,36),
  ('Madeline','Beach','male','1957-03-05','South Korea','Belfast','https://t.me/en-ca','http://walmart.com/one?gi=100','http://google.com/site?gi=100','vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae',84,37),
  ('Jordan','Munoz','male','1956-05-01','Colombia','Gorzów Wielkopolski','http://vz.ru/sub/cars','https://cnn.com/en-us?str=se','https://yahoo.com/group/9?page=1&offset=1','Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse',80,38),
  ('Lillith','Albert','male','1974-06-14','Russian Federation','Puntarenas','http://rbc.ru/site','http://zoom.us/settings?p=8','http://netflix.com/user/110?q=test','Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim,',70,39),
  ('Ignacia','Lang','male','1965-07-18','Singapore','Charleville-Mézières','https://livejournal.com/fr','https://naver.com/settings?q=11','http://cnn.com/group/9?g=1','at sem molestie sodales. Mauris blandit enim consequat purus.',56,40),
  ('Paki','Rodgers','male','1962-04-30','Chile','St. John''s','http://gismeteo.ru/sub','https://pinterest.com/settings?g=1','http://google.com/en-us?q=0','mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc',114,41),
  ('Cody','Massey','male','2006-10-30','United States','Tianjin','https://bbc.co.uk/fr','http://cnn.com/site?ad=115','https://wikipedia.org/sub/cars?q=11','sit amet, risus. Donec nibh enim, gravida sit amet, dapibus',15,42),
  ('Iona','Vaughn','male','1995-08-07','Vietnam','Remscheid','https://pinterest.com/sub/cars','http://whatsapp.com/one?client=g','https://google.com/one?q=0','metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor',133,43),
  ('Deacon','Ray','male','1952-05-09','Ukraine','Mohmand Agency','http://hh.ru/sub','https://reddit.com/one?q=4','https://twitter.com/one?str=se','erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan',140,44),
  ('Kessie','Adams','male','2004-06-05','China','Soledad de Graciano Sánchez','http://t.me/user/110','https://google.com/fr?ab=441&aad=2','http://naver.com/user/110?g=1','non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor',110,45),
  ('Hyacinth','Mccullough','male','1972-03-10','South Korea','Ereğli','https://kommersant.ru/sub','http://wikipedia.org/user/110?str=se','https://naver.com/sub?q=test','neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus',26,46),
  ('Cassandra','Moses','male','1993-09-14','Vietnam','Sechura','https://pikabu.ru/user/110','https://nytimes.com/sub/cars?search=1','http://walmart.com/sub/cars?q=4','in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et',94,47),
  ('Erin','Peters','male','1955-12-07','South Africa','Bajaur Agency','https://bbc.co.uk/sub/cars','http://twitter.com/en-us?g=1','http://nytimes.com/sub/cars?q=4','Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus',54,48),
  ('Reuben','Burris','male','1961-03-25','Indonesia','Punggol','http://ozon.ru/user/110','http://youtube.com/sub/cars?search=1&q=de','http://zoom.us/sub/cars?k=0','Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse',87,49),
  ('Joelle','Tucker','male','2009-06-27','Ukraine','Rạch Giá','https://yahoo.com/en-ca','http://twitter.com/settings?p=8','http://google.com/site?q=0','velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae',32,50);
INSERT INTO user_profiles (name,surname,gender,birthday,country,locality,personal_site,vk,twitter,about_yourself,avatar_image_id,user_id)
VALUES
  ('Carol','Kidd','male','2006-08-30','Singapore','Cambridge','http://turbopages.org/en-ca','http://ebay.com/user/110?q=11','https://google.com/site?str=se','faucibus orci luctus et ultrices posuere cubilia Curae Phasellus ornare. Fusce mollis.',47,51),
  ('Susan','Delgado','male','1995-12-26','Vietnam','Oslo','https://pinterest.com/sub/cars','https://naver.com/sub?q=0','http://whatsapp.com/site?page=1&offset=1','sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl.',50,52),
  ('Garth','Cain','male','1990-07-27','Philippines','Southaven','http://vz.ru/en-ca','http://reddit.com/settings?ad=115','https://baidu.com/user/110?q=0','Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis',84,53),
  ('Abbot','Kline','male','1972-08-21','Russian Federation','Palopo','http://google.ru/sub/cars','https://bbc.co.uk/en-ca?k=0','http://instagram.com/site?p=8','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet',113,54),
  ('Berk','Mcfadden','male','1966-08-17','Peru','Kostroma','https://gismeteo.ru/group/9','https://nytimes.com/user/110?q=0','https://google.com/group/9?ad=115','cubilia Curae Phasellus ornare. Fusce mollis. Duis sit amet diam eu',65,55),
  ('May','Anderson','male','2004-01-14','Turkey','Cambridge','http://tiktok.com/site','http://youtube.com/site?q=test','http://nytimes.com/user/110?p=8','nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum,',146,56),
  ('Rooney','Cooley','male','1970-09-26','Turkey','Ilhéus','https://naver.com/user/110','http://bbc.co.uk/one?p=8','https://zoom.us/site?q=0','eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit,',132,57),
  ('Pearl','Cantrell','male','1994-12-22','New Zealand','Mexico City','https://naver.com/sub','http://reddit.com/site?page=1&offset=1','https://pinterest.com/one?client=g','id enim. Curabitur massa. Vestibulum accumsan neque et nunc.',51,58),
  ('Gareth','Mercado','male','2006-09-12','Austria','Sapele','https://instagram.com/sub','http://google.com/en-ca?p=8','http://walmart.com/sub/cars?q=test','venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante',100,59),
  ('Alexandra','Hubbard','male','1970-05-06','Singapore','Ankara','http://google.com/sub','https://whatsapp.com/one?search=1&q=de','https://twitter.com/fr?client=g','diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per',46,60),
  ('Sopoline','Carroll','male','1975-08-17','Austria','Palembang','https://xnxx.com/site','https://cnn.com/site?str=se','http://instagram.com/group/9?k=0','orci luctus et ultrices posuere cubilia Curae Donec tincidunt. Donec vitae',42,61),
  ('Michael','Walters','male','1981-11-24','Turkey','Bellegem','http://vz.ru/settings','http://nytimes.com/site?str=se','http://wikipedia.org/settings?q=11','magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat',43,62),
  ('Leilani','Cash','male','2010-02-03','France','Parepare','https://ficbook.net/en-us','https://guardian.co.uk/group/9?search=1&q=de','http://yahoo.com/one?p=8','amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient',62,63),
  ('Malik','Morin','male','1989-10-13','Pakistan','Changi','https://t.me/en-ca','https://netflix.com/settings?client=g','https://reddit.com/site?search=1','Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra',72,64),
  ('Hayden','Pruitt','male','2014-10-29','Germany','Vanderbijlpark','http://wildberries.ru/group/9','https://baidu.com/settings?gi=100','https://reddit.com/group/9?k=0','tristique senectus et netus et malesuada fames ac turpis',132,65),
  ('Fletcher','Ashley','male','1970-12-26','Ukraine','Chuncheon','http://pinterest.com/en-us','http://netflix.com/en-us?g=1','https://reddit.com/user/110?ad=115','nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra',29,66),
  ('Sonya','Moore','male','2013-02-02','France','Flensburg','http://wikipedia.org/en-ca','http://reddit.com/fr?search=1&q=de','http://cnn.com/user/110?p=8','mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean',26,67),
  ('Keely','Daniels','male','2013-04-24','Colombia','Puerto Vallarta','http://rbc.ru/group/9','http://nytimes.com/one?q=4','https://reddit.com/group/9?q=test','metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien.',16,68),
  ('Xena','Houston','male','1987-11-13','Russian Federation','Gjøvik','http://naver.com/en-ca','https://yahoo.com/site?search=1','http://ebay.com/sub?page=1&offset=1','placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam',84,69),
  ('Logan','Pate','male','1983-03-15','Ukraine','Landeck','https://guardian.co.uk/settings','https://reddit.com/site?ab=441&aad=2','https://netflix.com/en-ca?k=0','orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus',119,70),
  ('Lilah','Mcintosh','male','2004-11-16','France','Ceuta','https://bbc.co.uk/site','http://twitter.com/one?q=0','http://baidu.com/one?ad=115','diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit.',41,71),
  ('Channing','Ramos','male','1988-03-03','New Zealand','Murmansk','http://turbopages.org/en-us','http://reddit.com/en-us?g=1','http://cnn.com/user/110?str=se','vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend.',16,72),
  ('Lenore','Baird','male','1975-01-17','New Zealand','Villa Alemana','https://instagram.com/en-ca','https://twitter.com/fr?k=0','http://netflix.com/settings?q=0','non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum',72,73),
  ('Sydnee','Nunez','male','1960-04-24','Costa Rica','Borno','https://kommersant.ru/sub','https://wikipedia.org/fr?str=se','http://facebook.com/en-us?search=1','mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit',114,74),
  ('Alexis','Mercer','male','1964-06-29','Vietnam','Conselice','http://news.mail.ru/group/9','https://cnn.com/site?q=test','http://wikipedia.org/en-us?ab=441&aad=2','rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer,',16,75),
  ('Duncan','Irwin','male','1957-03-04','Costa Rica','Cleveland','https://rambler.ru/en-ca','http://baidu.com/one?gi=100','https://bbc.co.uk/en-ca?p=8','Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula.',7,76),
  ('Fredericka','Carver','male','1977-01-15','Ukraine','Gdańsk','https://rbc.ru/settings','http://instagram.com/en-us?client=g','http://naver.com/user/110?g=1','feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula.',17,77),
  ('Serina','Bennett','male','1991-03-07','Poland','Dubbo','http://whatsapp.com/user/110','http://ebay.com/en-us?search=1&q=de','http://google.com/en-us?search=1','Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi',45,78),
  ('Grace','Scott','male','2008-12-06','Nigeria','Bontang','http://rbc.ru/sub/cars','http://ebay.com/en-ca?client=g','https://netflix.com/en-ca?ab=441&aad=2','Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac',145,79),
  ('Cooper','Holmes','male','1994-01-11','Spain','Lysychansk','https://twitter.com/site','https://walmart.com/user/110?ab=441&aad=2','http://wikipedia.org/site?gi=100','malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada',49,80);
INSERT INTO user_profiles (name,surname,gender,birthday,country,locality,personal_site,vk,twitter,about_yourself,avatar_image_id,user_id)
VALUES
  ('Kelsie','Leach','male','1977-03-29','Pakistan','Limón (Puerto Limón]','https://vz.ru/en-us','http://instagram.com/one?str=se','https://twitter.com/one?search=1','lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede',138,81),
  ('Wayne','Berry','male','1978-01-26','Ireland','Bayugan','http://gazeta.ru/en-ca','https://facebook.com/en-ca?q=4','http://yahoo.com/site?p=8','ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet posuere, enim',28,82),
  ('Tyrone','Cooley','male','1989-06-26','Netherlands','Cork','https://aliex/en-us','http://naver.com/user/110?client=g','https://facebook.com/en-ca?g=1','Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In',22,83),
  ('Prescott','Bender','male','2014-09-24','Brazil','Créteil','http://vz.ru/fr','https://nytimes.com/sub?q=4','https://wikipedia.org/fr?q=test','nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus.',118,84),
  ('Forrest','Nicholson','male','1999-02-07','Sweden','Queenstown','https://kommersant.ru/sub','https://bbc.co.uk/en-ca?client=g','http://baidu.com/sub?ab=441&aad=2','sem mollis dui, in sodales elit erat vitae risus. Duis a mi',25,85),
  ('Kasper','Hammond','male','1987-10-14','Peru','São José','https://naver.com/sub','http://whatsapp.com/en-us?q=test','http://instagram.com/site?page=1&offset=1','ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum,',73,86),
  ('Vivien','Cole','male','1995-06-30','China','Trujillo','https://sports.ru/group/9','http://ebay.com/sub/cars?search=1','https://google.com/settings?page=1&offset=1','odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci.',29,87),
  ('Nicholas','Gibson','male','1981-10-09','Brazil','Belford Roxo','http://pikabu.ru/fr','http://pinterest.com/fr?p=8','https://zoom.us/sub?page=1&offset=1','tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis',56,88),
  ('Chiquita','Wilkerson','male','2014-08-09','Sweden','Okpoko','http://gismeteo.ru/sub/cars','https://reddit.com/site?gi=100','https://zoom.us/en-ca?k=0','ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc',86,89),
  ('Akeem','Barrera','male','1976-12-23','Peru','Trollhättan','https://ress.ru/sub/cars','http://ebay.com/sub/cars?q=11','https://facebook.com/fr?q=4','sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque',20,90),
  ('Jada','Guy','male','1956-07-26','India','Chañaral','https://music.yandex.ru/settings','https://youtube.com/group/9?page=1&offset=1','https://bbc.co.uk/en-ca?gi=100','gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat.',112,91),
  ('Aline','Wong','male','2000-05-29','Poland','Irpin','http://gazeta.ru/user/110','https://bbc.co.uk/group/9?q=11','https://pinterest.com/en-us?q=test','vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque',147,92),
  ('Travis','Boyle','male','2001-11-21','Peru','Cabuyao','http://news.rambler.ru/en-us','https://google.com/one?page=1&offset=1','http://guardian.co.uk/en-ca?q=4','Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus',18,93),
  ('Yardley','Bradley','male','1957-04-30','Netherlands','Memphis','https://whatsapp.com/sub/cars','http://whatsapp.com/sub?q=4','http://cnn.com/user/110?q=4','Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus',135,94),
  ('Anika','Flynn','male','1965-02-23','Russian Federation','Cork','https://drive2.ru/sub/cars','http://walmart.com/settings?search=1&q=de','https://cnn.com/group/9?q=test','amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque',77,95),
  ('Baxter','Yang','male','1963-06-12','Peru','Bielefeld','http://t.me/sub/cars','https://baidu.com/settings?ad=115','http://yahoo.com/fr?client=g','gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam',28,96),
  ('Danielle','Livingston','male','1958-01-07','Brazil','Sorsogon City','https://bbc.co.uk/user/110','http://ebay.com/one?str=se','http://wikipedia.org/settings?ab=441&aad=2','leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce',25,97),
  ('Wyoming','Wallace','male','1959-06-11','Ireland','Puerto Carreño','http://drive2.ru/settings','https://bbc.co.uk/sub/cars?client=g','https://netflix.com/one?ad=115','eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit',145,98),
  ('Colby','Mcdowell','male','1973-12-08','Canada','Río Claro','http://pikabu.ru/group/9','http://netflix.com/en-ca?q=4','https://wikipedia.org/sub/cars?search=1&q=de','Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh',26,99),
  ('Drake','Monroe','male','1964-01-08','Nigeria','Cartagena','http://kommersant.ru/sub','http://google.com/sub/cars?gi=100','https://whatsapp.com/settings?search=1','vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla',149,100);
INSERT INTO user_profiles (name,surname,gender,birthday,country,locality,personal_site,vk,twitter,about_yourself,avatar_image_id,user_id)
VALUES
  ('Edward','Hogan','male','1956-12-08','Nigeria','Verdalsøra','http://hh.ru/en-ca','https://walmart.com/site?page=1&offset=1','https://twitter.com/fr?q=4','eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla',32,101),
  ('Madonna','Coffey','male','2010-12-17','Spain','Bathgate','http://livejournal.com/one','https://baidu.com/group/9?q=0','https://bbc.co.uk/site?q=0','placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend',131,102),
  ('Blossom','Woodard','male','2003-05-28','Netherlands','Neufeld an der Leitha','http://avito.ru/group/9','http://facebook.com/site?q=0','http://baidu.com/fr?ab=441&aad=2','ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi',66,103),
  ('Jeanette','Garrison','male','2005-01-03','Australia','Lanark','http://netflix.com/en-ca','https://wikipedia.org/fr?q=4','https://cnn.com/fr?q=4','a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis,',75,104),
  ('Hammett','Gibson','male','1981-05-20','China','Belfast','https://nytimes.com/fr','http://nytimes.com/group/9?page=1&offset=1','http://wikipedia.org/sub?client=g','ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris',134,105),
  ('Deirdre','Bishop','male','1974-10-04','Ukraine','Dörtyol','http://guardian.co.uk/one','https://nytimes.com/group/9?g=1','http://yahoo.com/sub/cars?q=11','lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque',125,106),
  ('Katell','Branch','male','1986-06-29','United Kingdom','Bannu','https://tiktok.com/site','http://baidu.com/en-ca?q=11','http://ebay.com/sub?ab=441&aad=2','dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam',27,107),
  ('Lara','Harrington','male','1960-11-07','Netherlands','Kendari','http://wildberries.ru/settings','https://cnn.com/sub/cars?q=11','https://instagram.com/settings?p=8','urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas',127,108),
  ('Harriet','Hays','male','1966-04-12','South Korea','Ust-Katav','https://drive2.ru/sub/cars','https://guardian.co.uk/settings?p=8','http://twitter.com/one?ab=441&aad=2','egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta',45,109),
  ('Carson','Lee','male','1975-01-22','Pakistan','Hall in Tirol','http://sberbank.ru/en-ca','http://netflix.com/fr?p=8','https://nytimes.com/en-us?gi=100','erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas',99,110),
  ('Astra','Stanton','male','1957-11-15','Chile','Butte','http://pikabu.ru/sub/cars','https://google.com/settings?ab=441&aad=2','https://ebay.com/group/9?q=4','nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere',23,111),
  ('Sopoline','Hicks','male','2000-05-15','Netherlands','Huacho','https://cloud.mail.ru/sub/cars','http://wikipedia.org/group/9?p=8','http://ebay.com/group/9?g=1','adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper,',111,112),
  ('Vera','Farley','male','2003-10-26','United Kingdom','Lạng Sơn','https://gazeta.ru/user/110','http://facebook.com/group/9?gi=100','https://twitter.com/site?k=0','luctus et ultrices posuere cubilia Curae Phasellus ornare. Fusce mollis.',15,113),
  ('Kellie','Valenzuela','male','1969-12-14','Canada','Metro','https://wikipedia.org/site','http://baidu.com/user/110?g=1','https://nytimes.com/en-ca?gi=100','ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur',54,114),
  ('Theodore','Mcneil','male','1991-12-14','Italy','Zaporizhzhia','http://guardian.co.uk/sub','http://nytimes.com/group/9?str=se','https://walmart.com/user/110?q=0','egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate',23,115),
  ('Kellie','Townsend','male','1990-02-04','Chile','Móstoles','https://whatsapp.com/group/9','https://netflix.com/user/110?client=g','https://naver.com/en-us?ad=115','facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa.',47,116),
  ('Linda','Hayden','male','1994-03-15','Vietnam','Phan Rang–Tháp Chàm','http://2gis.ru/sub','http://facebook.com/en-us?search=1&q=de','http://instagram.com/sub?gi=100','nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi',89,117),
  ('Imelda','Fernandez','male','1965-12-19','Nigeria','Jaén','https://baidu.com/fr','https://facebook.com/group/9?page=1&offset=1','https://baidu.com/one?q=0','erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu',84,118),
  ('Todd','Leblanc','male','1979-06-22','Belgium','Bagh','https://youtube.com/en-us','http://guardian.co.uk/group/9?q=4','https://netflix.com/fr?g=1','Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc,',32,119),
  ('Doris','Lloyd','male','1988-10-20','Brazil','Phong Thổ','https://xnxx.com/en-ca','http://baidu.com/sub/cars?client=g','http://whatsapp.com/group/9?p=8','vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed',114,120),
  ('Cruz','Riggs','male','1973-12-16','United States','Parys','https://walmart.com/en-us','http://whatsapp.com/sub?search=1','http://youtube.com/en-us?page=1&offset=1','hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris',136,121),
  ('Cody','Whitehead','male','1951-06-06','Vietnam','Kohima','https://walmart.com/sub','https://wikipedia.org/one?q=test','http://naver.com/one?q=11','conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In',137,122),
  ('Amelia','Small','male','2000-03-22','Vietnam','Tomaszów Mazowiecki','https://vk.com/user/110','http://google.com/site?ad=115','https://yahoo.com/one?client=g','Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus',146,123),
  ('Larissa','Mccarthy','male','1953-07-19','Turkey','Épernay','https://guardian.co.uk/settings','https://instagram.com/one?k=0','http://pinterest.com/one?q=4','lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend.',147,124),
  ('Maris','Nixon','male','2008-06-01','Turkey','Quesada','http://instagram.com/site','https://ebay.com/en-us?search=1','https://naver.com/en-us?client=g','et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum.',128,125),
  ('Vanna','Ballard','male','1977-07-11','Germany','Ansfelden','http://ok.ru/settings','https://naver.com/group/9?q=11','https://guardian.co.uk/fr?search=1&q=de','sed turpis nec mauris blandit mattis. Cras eget nisi dictum',149,126),
  ('Ignacia','Giles','male','1951-05-30','Ukraine','Caxias do Sul','http://walmart.com/en-us','https://zoom.us/en-us?gi=100','http://zoom.us/en-ca?str=se','metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede,',96,127),
  ('Griffin','Callahan','male','2003-11-27','Pakistan','Wrigley','http://ozon.ru/site','http://ebay.com/sub/cars?gi=100','http://google.com/site?search=1&q=de','fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam.',53,128),
  ('Lucas','Stevenson','male','1963-05-21','Germany','Da Lat','https://fandom.com/one','http://netflix.com/fr?client=g','http://instagram.com/sub/cars?q=11','Duis cursus, diam at pretium aliquet, metus urna convallis',111,129),
  ('Herrod','Reed','male','1984-07-10','Nigeria','Camaragibe','http://samsung.com/user/110','http://youtube.com/site?ab=441&aad=2','http://google.com/one?q=test','Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus.',39,130);
INSERT INTO user_profiles (name,surname,gender,birthday,country,locality,personal_site,vk,twitter,about_yourself,avatar_image_id,user_id)
VALUES
  ('Chloe','Haney','male','1981-07-24','Pakistan','Đồng Hới','http://whatsapp.com/sub/cars','https://twitter.com/en-ca?gi=100','https://pinterest.com/en-ca?search=1&q=de','vitae risus. Duis a mi fringilla mi lacinia mattis. Integer',118,131),
  ('Haley','Deleon','male','2007-08-08','Austria','Makiivka','http://facebook.com/en-us','http://instagram.com/fr?str=se','https://ebay.com/fr?str=se','dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor',7,132),
  ('Halee','Washington','male','2009-12-13','Norway','Lublin','http://bbc.co.uk/group/9','https://yahoo.com/user/110?p=8','http://instagram.com/settings?page=1&offset=1','nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus',4,133),
  ('Judah','Hodges','male','1954-07-19','Mexico','Alençon','https://yahoo.com/user/110','https://pinterest.com/one?k=0','https://cnn.com/one?str=se','volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam',35,134),
  ('Igor','Sellers','male','1986-05-16','Belgium','Cartagena','https://2gis.ru/en-us','http://walmart.com/en-ca?str=se','http://whatsapp.com/site?str=se','turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus.',43,135),
  ('Graham','Wagner','male','1952-06-02','Ukraine','Waitara','http://2gis.ru/user/110','http://guardian.co.uk/user/110?g=1','http://yahoo.com/one?ab=441&aad=2','ligula elit, pretium et, rutrum non, hendrerit id, ante.',83,136),
  ('Mason','Roberson','male','1989-11-05','Turkey','Dordrecht','http://kommersant.ru/fr','http://ebay.com/sub?str=se','http://wikipedia.org/one?ab=441&aad=2','sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing',28,137),
  ('Hayfa','Mclean','male','1957-08-29','Vietnam','Frankston','http://whatsapp.com/en-us','http://zoom.us/site?gi=100','https://youtube.com/en-us?q=test','dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor.',3,138),
  ('Fuller','Carson','male','2003-05-24','Netherlands','Lutsk','http://wildberries.ru/one','https://pinterest.com/user/110?q=11','http://whatsapp.com/settings?str=se','Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis',92,139),
  ('Louis','Sampson','male','2009-08-28','Philippines','Stargard Szczeciński','https://google.com/sub/cars','https://twitter.com/sub/cars?ad=115','https://zoom.us/user/110?str=se','scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis',64,140),
  ('Hyacinth','Luna','male','1970-08-11','Austria','Ciudad Apodaca','http://reddit.com/user/110','https://nytimes.com/site?page=1&offset=1','https://zoom.us/settings?page=1&offset=1','Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis',22,141),
  ('Jordan','Malone','male','1985-01-28','Indonesia','Makassar','http://cloud.mail.ru/fr','https://nytimes.com/fr?search=1','https://walmart.com/settings?search=1','tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt,',128,142),
  ('Ira','Powell','male','1980-12-22','Singapore','Kapfenberg','https://wikipedia.org/sub/cars','http://guardian.co.uk/site?page=1&offset=1','http://reddit.com/site?ab=441&aad=2','Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at',54,143),
  ('Melanie','Fisher','male','2014-09-05','Chile','Fauske','http://walmart.com/en-ca','https://facebook.com/sub/cars?search=1&q=de','https://netflix.com/fr?gi=100','posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum',119,144),
  ('Farrah','Sullivan','male','1986-04-18','China','Gouda','https://rbc.ru/user/110','http://cnn.com/en-us?k=0','https://youtube.com/site?k=0','sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris.',1,145),
  ('Rogan','Garner','male','1966-09-22','Germany','Zwolle','http://youtube.com/one','https://instagram.com/group/9?k=0','https://twitter.com/en-ca?ab=441&aad=2','non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',60,146),
  ('Echo','Alford','male','1960-02-09','Colombia','Sangju','https://yahoo.com/settings','https://netflix.com/site?gi=100','https://facebook.com/one?str=se','malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras',71,147),
  ('Finn','Alston','male','1998-11-23','Vietnam','Oryol','http://facebook.com/one','https://zoom.us/sub/cars?p=8','http://yahoo.com/fr?ad=115','urna justo faucibus lectus, a sollicitudin orci sem eget massa.',29,148),
  ('Rebecca','Kirkland','male','1999-04-22','France','Kilsyth','https://rbc.ru/site','http://cnn.com/group/9?page=1&offset=1','https://google.com/sub/cars?k=0','Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique',82,149),
  ('Maggie','Lynch','male','2002-10-25','China','Karak','https://drom.ru/en-ca','http://wikipedia.org/en-ca?page=1&offset=1','http://naver.com/group/9?q=4','sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum,',131,150);